/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ukk_p1;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author micro
 */
public class login extends javax.swing.JFrame {
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();
    

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        k.connect();
    }
    
    class user{
    String nik, nama, foto="";
    public user(){
        nik = text_nk.getText();
        nama = text_lengkap.getText();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_nk = new javax.swing.JTextField();
        text_lengkap = new javax.swing.JTextField();
        text_regis = new javax.swing.JButton();
        btn_masuk = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tampilan Login");
        setBackground(new java.awt.Color(0, 70, 67));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 30, 29));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selamat Datang DiAplikasi PeduliDiri");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 40, 200, 15);

        jLabel2.setBackground(new java.awt.Color(0, 30, 29));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAMA LENGKAP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 140, 88, 15);

        text_nk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nkActionPerformed(evt);
            }
        });
        getContentPane().add(text_nk);
        text_nk.setBounds(140, 70, 180, 30);
        getContentPane().add(text_lengkap);
        text_lengkap.setBounds(140, 130, 180, 31);

        text_regis.setBackground(new java.awt.Color(249, 188, 105));
        text_regis.setForeground(new java.awt.Color(0, 30, 29));
        text_regis.setText("REGISTRASI");
        text_regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_regisActionPerformed(evt);
            }
        });
        getContentPane().add(text_regis);
        text_regis.setBounds(30, 190, 120, 40);

        btn_masuk.setBackground(new java.awt.Color(249, 188, 105));
        btn_masuk.setForeground(new java.awt.Color(0, 30, 29));
        btn_masuk.setText("MASUK");
        btn_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masukActionPerformed(evt);
            }
        });
        getContentPane().add(btn_masuk);
        btn_masuk.setBounds(190, 190, 130, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LOGIN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 10, 60, 22);

        jLabel5.setBackground(new java.awt.Color(0, 30, 29));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NIK");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 80, 19, 15);

        jPanel1.setBackground(new java.awt.Color(0, 70, 67));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 250);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void text_nkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nkActionPerformed

    private void text_regisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_regisActionPerformed
        // TODO add your handling code here:
        registrasi reg = new registrasi();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_text_regisActionPerformed

    private void btn_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masukActionPerformed
        // TODO add your handling code here:
        user u = new user();
        try {
            this.stat = k.getCon().prepareStatement("select * from user where " + "nik='"+u.nik+"' and nama='"+u.nama+"';");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
                u.foto = rs.getString("foto");
                
            }
            if (u.foto.equals("")) {
                JOptionPane.showMessageDialog(null, "Akun Tidak di Temukan");
            }else{
                menu_utama m = new menu_utama();
                m.setNik(u.nik);
                m.setNama(u.nama);
                m.setFoto(u.foto);
                m.refreshFoto();
                m.setVisible(true);
                this.setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_masukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_masuk;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField text_lengkap;
    private javax.swing.JTextField text_nk;
    private javax.swing.JButton text_regis;
    // End of variables declaration//GEN-END:variables
}
