/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ukk_p1;

import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author micro
 */
public class registrasi extends javax.swing.JFrame {
    private PreparedStatement stat;
    private ResultSet rs;
    private String filename;
    koneksi k = new koneksi();

    /**
     * Creates new form registrasi
     */
    public registrasi() {
        initComponents();
        k.connect();
    }
    
    class akun extends registrasi{
        String nik = "", nama="", foto="";
        public akun(){
            nik = text_nik.getText();
            nama = text_nama.getText();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_nk = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_nik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_pilihfoto = new javax.swing.JButton();
        label_foto = new javax.swing.JLabel();
        btn_daftar = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        text_nk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_nk.setForeground(new java.awt.Color(255, 255, 255));
        text_nk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_nk.setText("REGISTRASI");
        getContentPane().add(text_nk);
        text_nk.setBounds(10, 11, 451, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIK");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 85, 19, 15);
        getContentPane().add(text_nik);
        text_nik.setBounds(158, 77, 303, 32);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAMA LENGKAP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 140, 88, 15);
        getContentPane().add(text_nama);
        text_nama.setBounds(158, 133, 303, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("UPLOAD FOTO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 200, 82, 15);

        btn_pilihfoto.setBackground(new java.awt.Color(249, 188, 105));
        btn_pilihfoto.setForeground(new java.awt.Color(0, 30, 29));
        btn_pilihfoto.setText("PILIH FOTO");
        btn_pilihfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihfotoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pilihfoto);
        btn_pilihfoto.setBounds(158, 191, 146, 35);

        label_foto.setForeground(new java.awt.Color(255, 255, 255));
        label_foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 188, 105)));
        getContentPane().add(label_foto);
        label_foto.setBounds(158, 237, 146, 190);

        btn_daftar.setBackground(new java.awt.Color(249, 188, 105));
        btn_daftar.setForeground(new java.awt.Color(0, 30, 29));
        btn_daftar.setText("DAFTAR");
        btn_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_daftar);
        btn_daftar.setBounds(24, 454, 195, 41);

        btn_cancel.setBackground(new java.awt.Color(249, 188, 105));
        btn_cancel.setForeground(new java.awt.Color(0, 30, 29));
        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel);
        btn_cancel.setBounds(255, 454, 195, 40);

        jPanel1.setBackground(new java.awt.Color(0, 70, 67));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 470, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pilihfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihfotoActionPerformed
        // TODO add your handling code here:
        akun a = new akun();
        if (a.nik.equals("") || a.nama.equals("")) {
            JOptionPane.showMessageDialog(null, "NIK dan NAMA tidak Boleh Kosong");
        }else{
            try {
                JFileChooser chooser = new JFileChooser();
                chooser.showOpenDialog(null);
                File f = chooser.getSelectedFile();
                ImageIcon icon = new ImageIcon(f.toString());
                Image img = icon.getImage().getScaledInstance(label_foto.getWidth(), label_foto.getHeight(), Image.SCALE_DEFAULT);
                ImageIcon ic = new ImageIcon(img);
                label_foto.setIcon(ic);
                this.filename = f.getAbsolutePath();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_pilihfotoActionPerformed

    private void btn_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftarActionPerformed
        // TODO add your handling code here:
        try {
            String newpath = "src/upload";
            File directory = new File(newpath);
            if (!directory.exists()) {
                directory.mkdirs();
            }
            File fileawal = null;
            File fileakhir = null;
            String ext = this.filename.substring(filename.lastIndexOf('.')+1);
            fileawal = new File(filename);
            fileakhir = new File(newpath+"/"+text_nik.getText()+"."+ext);
            System.out.println(fileakhir);
            akun a = new akun();
            this.stat = k.getCon().prepareStatement("insert into user values(?,?,?)");
            stat.setString(1, a.nik);
            stat.setString(2, a.nama);
            stat.setString(3, fileakhir.toString());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Akun Sudah Terdaftar, Silahkan Kembali Login");
            Files.copy(fileawal.toPath(), fileakhir.toPath());
            login log = new login();
            log.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_daftarActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        login log = new login();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_daftar;
    private javax.swing.JButton btn_pilihfoto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_foto;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_nik;
    private javax.swing.JLabel text_nk;
    // End of variables declaration//GEN-END:variables
}
